### ISSUE TITLE
Schemas are not found to validate against

### ISSUE THREAD

**Issue by tomkerkhove** [urcomputeringpal/kubevalidator#55]
**Describe the bug**
Schemas are not found to validate against and fails with error:
> Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.10.0-standalone-strict/deployments.json: Could not read schema from HTTP, response status is 404 Not Found

Please note the `/deployments.json` instead of `/deployment.json`.

**To Reproduce**
1. Configure schema v1.10
2. Schema not found

**Expected behavior**
Schemas are being resolved successfully

**Additional context**
You can find an example here - https://github.com/tomkerkhove/promitor/pull/263/checks?check_run_id=43687546

**Comment by jnewland** [comment]
Thanks for the report!  "deployments" is not a valid kind, but "deployment" is. This looks like a case where a better error message would help. I'm tracking that in https://github.com/urcomputeringpal/kubevalidator/issues/53, and should have an improvement here soon.

**Comment by tomkerkhove** [comment]
`Deployments` is indeed not valid but it gave a weird error as you've mentioned.
Thanks for improving!
